import coverImage from "../images/2000xs.jpg";
import img1 from "../images/2000xs.jpg";
import img2 from "../images/2000xs.jpg";
import img3 from "../images/2000xs.jpg";
import img4 from "../images/2000xs.jpg";
export const fleet = [
  {
    name: "Eldoris",
    title: "ELDORIS",
    subTitle: "2011 Bavaria 45 Cruiser",
    paragraph: "Fast and luxurios; the complete sailing superyacht experience",
    description: `Twilight was designed with two specific design requests from an experienced owner who has built more than a thousand yachts: make it fast and comfortable. Designed by Ed Dubios, this yacht has certainly exceeded the brief in this luxurious and powerful high-performance sailing superyacht.`,
    specs: {
      capacity: "3 guests",
      motor: "75HP Volvo",
      fuel: "210 litres",
      water: "360 litres",
      wc: "3 Elektrikli WC",
      length: "14m",
    },
    features: [
      "Buzdolabı",
      "Derin dondurucu",
      "Güneşlenme alanı",
      "Nevresim takımı ve havlular",
      "Derinlik göstergesi",
      "Hoparlör",
      "Ocak",
      "Fırın",
      "CD oynatıcı",
      "Pusula",
      "Yangın söndürme tüpleri",
      "Telsiz",
      "Can yeleği",
      "Can sali",
      "El feneri",
      "Acil durum fişekleri",
      "Hız göstergesi",
      "Güneş paneli",
      "Rüzgar göstergesi",
      "Navigasyon",
      "Klima (Salon)",
      "Otopilot",
      "Güneşlik",
      "Baş pervane",
      "Webasto",
      "Şnorkel",
      "GPS",
      "Usb MP3",
      "Teak kokpit",
    ],
    coverImage: coverImage,
    images: [img1, img2, img3, img4],
  },
];
